# Generated by Django 4.2.7 on 2025-07-20 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UniFiController",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
                ("site_id", models.CharField(default="default", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oauth_provider", models.CharField(blank=True, max_length=50)),
                ("oauth_uid", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("member", "Member"),
                            ("guest", "Guest"),
                            ("event", "Event Attendee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Floor 1"),
                            ("2", "Floor 2"),
                            ("3", "Floor 3"),
                            ("4", "Floor 4"),
                            ("5", "Floor 5"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "member_name",
                    models.CharField(
                        blank=True,
                        help_text="For guests: name of member they're visiting",
                        max_length=100,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        blank=True,
                        help_text="For event attendees: event name",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortalSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(help_text="Device MAC address", max_length=17),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("unifi_session_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Authorization"),
                            ("authorized", "Authorized"),
                            ("expired", "Expired"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
